CREATE TABLE A_ALOHANDES ( 
    TIEMPO_MINIMO_VC NUMBER NOT NULL,  
    TIEMPO_MINIMO_VE NUMBER NOT NULL,  
    MAXIMO_DIAS_VE NUMBER NOT NULL  
);

CREATE TABLE A_TIPOUSUARIO (
    ID NUMBER,
    TIPOUSUARIO VARCHAR(30) NOT NULL,
    CONSTRAINT A_TIPOUSUARIO_PK PRIMARY KEY (ID)
);

CREATE TABLE A_USUARIO (
    ID NUMBER,
    TIPOUSUARIO NUMBER NOT NULL, 
    NOMBRE VARCHAR(40),
    CONSTRAINT A_USUARIO_PK PRIMARY KEY (ID),
    CONSTRAINT A_USUARIO_FK_TIPOUSUARIO FOREIGN KEY (TIPOUSUARIO) REFERENCES A_TIPOUSUARIO(ID)
);

CREATE TABLE A_SEGUROARRENDAMIENTO (
    ID NUMBER, 
    DESCRIPCION VARCHAR(200) NOT NULL,
    CONSTRAINT A_SEGUROARRENDAMIENTO_PK PRIMARY KEY (ID)
);

CREATE TABLE A_HORARIO (
    ID NUMBER, 
    HORAAPERTURA TIMESTAMP,
    HORACIERRE TIMESTAMP,
    CONSTRAINT A_HORARIO_PK PRIMARY KEY (ID)
);

CREATE TABLE A_TIPOESTABLECIMIENTO (
    ID NUMBER, 
    TIPOESTABLECIMIENTO VARCHAR(30) NOT NULL,
    CONSTRAINT A_TIPOESTABLECIMIENTO_PK PRIMARY KEY (ID)
);

CREATE TABLE A_ESTABLECIMIENTO (
    ID NUMBER,
    NOMBRE VARCHAR(30) NOT NULL, 
    DIRECCION VARCHAR (30) NOT NULL, 
    COSTO NUMBER NOT NULL, 
    PORDIAOMES NUMBER(1) NOT NULL,
    ACTIVO NUMBER(1) NOT NULL,
    TIPOESTABLECIMIENTO NUMBER NOT NULL,
    IDSEGUROARRENDAMIENTO NUMBER,
    IDHORARIO NUMBER,
    IDDUENIO NUMBER NOT NULL,
    CONSTRAINT A_ESTABLECIMIENTO_PK PRIMARY KEY (ID),
    CONSTRAINT A_ESTABLECIMIENTO_FK_TIPO FOREIGN KEY (TIPOESTABLECIMIENTO) REFERENCES A_TIPOESTABLECIMIENTO(ID),
    CONSTRAINT A_ESTABLECIMIENTO_FK_IDSEGURO FOREIGN KEY (IDSEGUROARRENDAMIENTO) REFERENCES A_SEGUROARRENDAMIENTO(ID),
    CONSTRAINT A_ESTABLECIMIENTO_FK_IDHORARIO FOREIGN KEY (IDHORARIO) REFERENCES A_HORARIO(ID),
    CONSTRAINT A_ESTABLECIMIENTO_FK_IDDUENIO FOREIGN KEY (IDDUENIO) REFERENCES A_USUARIO(ID)
);
	
CREATE TABLE A_ARRIENDO (
    ID NUMBER,
    FECHAINICIO DATE NOT NULL,
    DURACION NUMBER NOT NULL,
    DESCUENTO NUMBER,
    ESTADO VARCHAR(15) NOT NULL,
    IDESTABLECIMIENTO NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL, 
    CONSTRAINT A_ARRIENDO_PK PRIMARY KEY (ID),
    CONSTRAINT A_ARRIENDO_FK_IDESTABL FOREIGN KEY (IDESTABLECIMIENTO) REFERENCES A_ESTABLECIMIENTO(ID),
    CONSTRAINT A_ARRIENDO_FK_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES A_USUARIO(ID)
);

CREATE TABLE A_CARACTERISTICAE (
    ID NUMBER,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(255), 
    COSTO NUMBER,
    IDESTABLECIMIENTO NUMBER,
    CONSTRAINT A_CARACTERISTICAE_PK PRIMARY KEY (ID),
    CONSTRAINT A_CARACTERISTICAE_FK_IDE FOREIGN KEY (IDESTABLECIMIENTO) REFERENCES A_ESTABLECIMIENTO(ID)
);

CREATE TABLE A_HABITACION (
    ID NUMBER,
    NUMEROHABITACION NUMBER,
    CAPACIDAD NUMBER,
    COSTO NUMBER,
    COMPARTIDA NUMBER(1),
    IDESTABLECIMIENTO NUMBER,
    CONSTRAINT A_HABITACION_PK PRIMARY KEY (ID),
    CONSTRAINT A_HABITACION_FK_IDE FOREIGN KEY (IDESTABLECIMIENTO) REFERENCES A_ESTABLECIMIENTO(ID)
);

CREATE TABLE A_CARACTERISTICAH (
    ID NUMBER,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(255), 
    COSTO NUMBER,
    IDHABITACION NUMBER,
    CONSTRAINT A_CARACTERISTICAH_PK PRIMARY KEY (ID),
    CONSTRAINT A_CARACTERISTICAH_FK_IDH FOREIGN KEY (IDHABITACION) REFERENCES A_HABITACION(ID)
);

COMMIT;




